# Generated by Django 3.0.4 on 2020-03-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Produto',
        ),
    ]
