# Generated by Django 3.0.4 on 2020-03-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20200315_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='modelo',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='produto',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
